# program to find arithmetic operation
a=int(input("Enter the first number: "))
b=int(input("Enter the second number: "))
c=(a+b)
d=(a-b)
e=(a*b)
f=(a/b)
print("Sum=",c)
print("Difference=",d)
print("Product=",e)
print("Division=",f)