import math
n=eval(input("Enter the number: "))
print("Float Absolute value of ",n," is: ",math.fabs(n))
print("Ceil value of ",n," is: ",math.ceil(n))
print("Floor value of ",n," is: ",math.floor(n))
print("Exponential value of ",n," is: ",math.exp(n))
print("Log value of ",n," is: ",math.log(n))
print("Natural logarithm value of", n, "is:", math.log10(n))
print("Sine value of ",n," is: ",math.sin(n))
print("Cosine value of ",n," is: ",math.cos(n))
print("Tangent value of ",n," is: ",math.tan(n))
print("Degrees value of ",n," is: ",math.degrees(n))
print("Radians value of ",n," is: ",math.radians(n))
print("Square root value of ",n," is: ",math.sqrt(n))