from numpy import *
n=int(input("Enter size of the array(nxn): "))
print("Enter the first matrix")
a=matrix([[input()for j in range(n)]for i in range(n)],int)
print("Enter the second matrix")
b=matrix([[input()for j in range(n)]for i in range(n)],int)
print("First matrix is:")
print(a)
print("Second matrix is:")
print(b)
print("Sum of the matrices:")
print(a+b)
print("Difference of the matrices:")
print(a-b)
print("Product of the matrices:")
print(a*b)
print("Transpose of first matrix:")
print(a.transpose())